export const seedProfiles = [
  {
    id: "profile-asha",
    name: "Asha Reddy",
    email: "asha.reddy@psu.edu",
    university: "Penn State University",
    city: "State College",
    state: "PA",
    program: "MS Computer Science",
    country: "India",
    arrivalDate: "2026-08-12",
    moveInDate: "2026-08-15",
    budgetMin: 650,
    budgetMax: 950,
    preferredAreas: ["Downtown", "West College", "Campus Shuttle"],
    leaseLength: "Fall semester",
    roomType: "Private room",
    genderPreference: "Women only",
    sleepSchedule: "Late",
    cleanliness: "Very tidy",
    cooking: "Vegetarian kitchen preferred",
    pets: "No pets",
    smoking: "No smoking",
    vibe: "Quiet study-focused apartment, close to buses, okay with temporary stay first.",
    verified: true,
    updatedAt: "2026-07-13T08:20:00.000Z"
  },
  {
    id: "profile-sofia",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@ucla.edu",
    university: "UCLA",
    city: "Los Angeles",
    state: "CA",
    program: "MS Electrical Engineering",
    country: "Mexico",
    arrivalDate: "2026-09-05",
    moveInDate: "2026-09-10",
    budgetMin: 1100,
    budgetMax: 1650,
    preferredAreas: ["Westwood", "Sawtelle", "Santa Monica Bus"],
    leaseLength: "Academic year",
    roomType: "Private room",
    genderPreference: "Women only",
    sleepSchedule: "Early",
    cleanliness: "Tidy",
    cooking: "Cooks often",
    pets: "No pets",
    smoking: "No smoking",
    vibe: "Needs a safe room near transit, prefers a calm apartment with other graduate students.",
    verified: true,
    updatedAt: "2026-07-13T07:55:00.000Z"
  },
  {
    id: "profile-omar",
    name: "Omar Hassan",
    email: "omar.hassan@utexas.edu",
    university: "University of Texas at Austin",
    city: "Austin",
    state: "TX",
    program: "MS Data Science",
    country: "Egypt",
    arrivalDate: "2026-08-08",
    moveInDate: "2026-08-10",
    budgetMin: 700,
    budgetMax: 1050,
    preferredAreas: ["West Campus", "North Campus", "Riverside Shuttle"],
    leaseLength: "6 months",
    roomType: "Shared apartment",
    genderPreference: "Men only",
    sleepSchedule: "Flexible",
    cleanliness: "Moderate",
    cooking: "Cooks often",
    pets: "No pets",
    smoking: "No smoking",
    vibe: "Looking for affordable short-term housing before signing a longer lease.",
    verified: true,
    updatedAt: "2026-07-13T06:50:00.000Z"
  },
  {
    id: "profile-mina",
    name: "Mina Park",
    email: "mina.park@nyu.edu",
    university: "New York University",
    city: "New York",
    state: "NY",
    program: "MS Integrated Design",
    country: "South Korea",
    arrivalDate: "2026-08-26",
    moveInDate: "2026-08-28",
    budgetMin: 1400,
    budgetMax: 2200,
    preferredAreas: ["Greenwich Village", "Downtown Brooklyn", "Jersey City PATH"],
    leaseLength: "12 months",
    roomType: "Private room",
    genderPreference: "No preference",
    sleepSchedule: "Late",
    cleanliness: "Very tidy",
    cooking: "Light cooking",
    pets: "Cat okay",
    smoking: "No smoking",
    vibe: "Open to commuting by subway if the apartment is verified and roommates are design or grad students.",
    verified: true,
    updatedAt: "2026-07-12T17:10:00.000Z"
  },
  {
    id: "profile-ananya-portland",
    name: "Ananya Iyer",
    email: "ananya.iyer@pdx.edu",
    university: "Portland State University",
    city: "Portland",
    state: "OR",
    program: "MS Applied Data Science",
    country: "India",
    arrivalDate: "2026-09-12",
    moveInDate: "2026-09-15",
    budgetMin: 800,
    budgetMax: 1250,
    preferredAreas: ["Downtown Portland", "Goose Hollow", "South Waterfront"],
    leaseLength: "Academic year",
    roomType: "Private room",
    genderPreference: "Women only",
    sleepSchedule: "Late",
    cleanliness: "Tidy",
    cooking: "Vegetarian kitchen preferred",
    pets: "No pets",
    smoking: "No smoking",
    vibe: "Looking for a calm room near MAX or streetcar access to Portland State.",
    verified: true,
    updatedAt: "2026-07-13T09:10:00.000Z"
  },
  {
    id: "profile-kenji-osu",
    name: "Kenji Tanaka",
    email: "kenji.tanaka@oregonstate.edu",
    university: "Oregon State University",
    city: "Corvallis",
    state: "OR",
    program: "MS Robotics",
    country: "Japan",
    arrivalDate: "2026-09-18",
    moveInDate: "2026-09-20",
    budgetMin: 650,
    budgetMax: 1050,
    preferredAreas: ["Monroe Ave", "North Corvallis", "Southtown"],
    leaseLength: "12 months",
    roomType: "Private room",
    genderPreference: "No preference",
    sleepSchedule: "Early",
    cleanliness: "Very tidy",
    cooking: "Light cooking",
    pets: "Cat okay",
    smoking: "No smoking",
    vibe: "Wants a quiet apartment within biking distance to OSU labs.",
    verified: true,
    updatedAt: "2026-07-13T09:00:00.000Z"
  }
];

export const seedListings = [
  {
    id: "listing-beaver",
    title: "The Meridian – Unit 304",
    apartmentName: "The Meridian",
    unitNumber: "304",
    university: "Penn State University",
    city: "State College",
    state: "PA",
    type: "Sublease",
    rent: 825,
    deposit: 400,
    availableFrom: "2026-08-14",
    availableTo: "2026-12-20",
    area: "Downtown",
    address: "E Beaver Ave, State College, PA",
    distanceToCampus: 0.4,
    furnished: true,
    utilitiesIncluded: ["Water", "Internet"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "Women only",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["Walk to campus", "Furnished", "International friendly"],
    description: "One private room in a 3B2B apartment. Current roommates are graduate students and prefer a quiet home.",
    postedBy: "Maya S.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T08:05:00.000Z"
  },
  {
    id: "listing-westwood",
    title: "Kelton House – Unit 512",
    apartmentName: "Kelton House",
    unitNumber: "512",
    university: "UCLA",
    city: "Los Angeles",
    state: "CA",
    type: "Sublease",
    rent: 1480,
    deposit: 800,
    availableFrom: "2026-09-08",
    availableTo: "2027-06-20",
    area: "Westwood",
    address: "Kelton Ave, Los Angeles, CA",
    distanceToCampus: 0.7,
    furnished: true,
    utilitiesIncluded: ["Water", "Internet"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "Women only",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["UCLA", "Furnished", "Video tour", "In-unit laundry"],
    description: "Private furnished room near UCLA with two quiet graduate roommates and a verified video walkthrough.",
    postedBy: "Priya N.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T07:45:00.000Z"
  },
  {
    id: "listing-austin-west",
    title: "The Block on 25th – Unit 408",
    apartmentName: "The Block on 25th",
    unitNumber: "408",
    university: "University of Texas at Austin",
    city: "Austin",
    state: "TX",
    type: "Shared room",
    rent: 925,
    deposit: 450,
    availableFrom: "2026-08-09",
    availableTo: "2027-05-15",
    area: "West Campus",
    address: "San Gabriel St, Austin, TX",
    distanceToCampus: 0.6,
    furnished: true,
    utilitiesIncluded: ["Internet"],
    roomType: "Shared apartment",
    roommatesNeeded: 1,
    genderPreference: "Men only",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["UT Austin", "Budget", "Walkable"],
    description: "Budget-friendly shared apartment close to UT Austin. Good for a student arriving before orientation.",
    postedBy: "Hassan M.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T07:35:00.000Z"
  },
  {
    id: "listing-nyu-brooklyn",
    title: "AVA Fort Greene – Unit 19B",
    apartmentName: "AVA Fort Greene",
    unitNumber: "19B",
    university: "New York University",
    city: "New York",
    state: "NY",
    type: "Lease takeover",
    rent: 1950,
    deposit: 1950,
    availableFrom: "2026-08-27",
    availableTo: "2027-08-01",
    area: "Downtown Brooklyn",
    address: "Jay St, Brooklyn, NY",
    distanceToCampus: 2.8,
    furnished: false,
    utilitiesIncluded: ["Water"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "No preference",
    pets: "Cat okay",
    smoking: "No smoking",
    tags: ["NYU", "Subway", "Verified host", "In-unit laundry", "Pet friendly"],
    description: "Private room with a direct subway route to NYU buildings. Host can provide lease documents before deposit.",
    postedBy: "Daniel R.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-12T20:40:00.000Z"
  },
  {
    id: "listing-boston",
    title: "The Fenway – Unit 6C",
    apartmentName: "The Fenway",
    unitNumber: "6C",
    university: "Northeastern University",
    city: "Boston",
    state: "MA",
    type: "Temporary stay",
    rent: 1180,
    deposit: 350,
    availableFrom: "2026-08-20",
    availableTo: "2026-09-18",
    area: "Fenway",
    address: "Hemenway St, Boston, MA",
    distanceToCampus: 0.5,
    furnished: true,
    utilitiesIncluded: ["Electric", "Water", "Internet"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "No preference",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["Short-term", "Northeastern", "Landing stay"],
    description: "Short-term furnished room for students who need a safe first place before their permanent lease begins.",
    postedBy: "Mei T.",
    verified: false,
    riskLevel: "medium",
    createdAt: "2026-07-12T18:10:00.000Z"
  },
  {
    id: "listing-psu-portland-goose",
    title: "Goose Hollow Lofts – Unit 304",
    apartmentName: "Goose Hollow Lofts",
    unitNumber: "304",
    university: "Portland State University",
    city: "Portland",
    state: "OR",
    type: "Sublease",
    rent: 1080,
    deposit: 500,
    availableFrom: "2026-09-12",
    availableTo: "2027-06-15",
    area: "Goose Hollow",
    address: "SW Jefferson St, Portland, OR",
    distanceToCampus: 0.5,
    furnished: true,
    utilitiesIncluded: ["Water", "Internet"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "Women only",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["Portland State", "MAX nearby", "Furnished"],
    description: "Private furnished room close to PSU and public transit, with a quiet graduate-student roommate.",
    postedBy: "Leah M.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T09:18:00.000Z"
  },
  {
    id: "listing-psu-portland-waterfront",
    title: "Osprey Apartments – Unit 512",
    apartmentName: "Osprey Apartments",
    unitNumber: "512",
    university: "Portland State University",
    city: "Portland",
    state: "OR",
    type: "Temporary stay",
    rent: 940,
    deposit: 250,
    availableFrom: "2026-09-01",
    availableTo: "2026-10-05",
    area: "South Waterfront",
    address: "SW Moody Ave, Portland, OR",
    distanceToCampus: 1.1,
    furnished: true,
    utilitiesIncluded: ["Electric", "Water", "Internet"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "No preference",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["Short-term", "Streetcar", "Landing stay"],
    description: "Short-term furnished room for students arriving in Portland before signing a permanent lease.",
    postedBy: "Noah B.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T09:05:00.000Z"
  },
  {
    id: "listing-osu-monroe",
    title: "The Sierra – Unit 208",
    apartmentName: "The Sierra",
    unitNumber: "208",
    university: "Oregon State University",
    city: "Corvallis",
    state: "OR",
    type: "Lease takeover",
    rent: 875,
    deposit: 450,
    availableFrom: "2026-09-18",
    availableTo: "2027-08-31",
    area: "Monroe Ave",
    address: "NW Monroe Ave, Corvallis, OR",
    distanceToCampus: 0.4,
    furnished: false,
    utilitiesIncluded: ["Water"],
    roomType: "Private room",
    roommatesNeeded: 1,
    genderPreference: "No preference",
    pets: "Cat okay",
    smoking: "No smoking",
    tags: ["OSU", "Bikeable", "Lease takeover"],
    description: "Private room close to Oregon State campus with bike storage and a quiet study routine.",
    postedBy: "Ethan C.",
    verified: true,
    riskLevel: "low",
    createdAt: "2026-07-13T08:55:00.000Z"
  },
  {
    id: "listing-uo-eugene",
    title: "Fifteen Oaks – Unit 8",
    apartmentName: "Fifteen Oaks",
    unitNumber: "8",
    university: "University of Oregon",
    city: "Eugene",
    state: "OR",
    type: "Shared room",
    rent: 760,
    deposit: 350,
    availableFrom: "2026-09-20",
    availableTo: "2027-06-30",
    area: "West University",
    address: "E 15th Ave, Eugene, OR",
    distanceToCampus: 0.3,
    furnished: true,
    utilitiesIncluded: ["Internet"],
    roomType: "Shared apartment",
    roommatesNeeded: 1,
    genderPreference: "No preference",
    pets: "No pets",
    smoking: "No smoking",
    tags: ["University of Oregon", "Walkable", "Budget"],
    description: "Affordable room in a student house near UO with a simple video tour before deposit.",
    postedBy: "Sofia L.",
    verified: false,
    riskLevel: "medium",
    createdAt: "2026-07-13T08:40:00.000Z"
  }
];

const seedConfirmationDates = {
  "listing-psu-portland-goose": "2026-07-28T09:18:00.000Z",
  "listing-psu-portland-waterfront": "2026-07-27T09:05:00.000Z",
  "listing-osu-monroe": "2026-07-25T08:55:00.000Z",
  "listing-uo-eugene": "2026-07-23T08:40:00.000Z",
  "listing-beaver": "2026-07-21T08:05:00.000Z",
  "listing-westwood": "2026-07-18T07:45:00.000Z",
  "listing-austin-west": "2026-07-16T07:35:00.000Z",
  "listing-nyu-brooklyn": "2026-07-11T20:40:00.000Z",
  "listing-boston": "2026-07-08T18:10:00.000Z"
};

seedListings.forEach((listing) => {
  listing.availabilityStatus = "available";
  listing.lastConfirmedAt = seedConfirmationDates[listing.id] || listing.createdAt;
});

const seedCostProfiles = {
  "listing-beaver": [70, 0, 0, 15, 0, 35],
  "listing-westwood": [110, 150, 0, 18, 35, 50],
  "listing-austin-west": [85, 95, 25, 15, 20, 40],
  "listing-nyu-brooklyn": [125, 0, 45, 20, 30, 75],
  "listing-boston": [95, 0, 35, 18, 25, 50],
  "listing-psu-portland-goose": [80, 120, 0, 15, 12, 45],
  "listing-psu-portland-waterfront": [65, 140, 0, 16, 20, 40],
  "listing-osu-monroe": [75, 35, 30, 14, 0, 35],
  "listing-uo-eugene": [90, 0, 0, 14, 15, 30]
};

seedListings.forEach((listing) => {
  const [utilitiesMonthly, parkingMonthly, internetMonthly, rentersInsuranceMonthly, otherMonthlyFees, applicationFee] =
    seedCostProfiles[listing.id] || [0, 0, 0, 0, 0, 0];
  Object.assign(listing, {
    utilitiesMonthly,
    parkingMonthly,
    internetMonthly,
    rentersInsuranceMonthly,
    otherMonthlyFees,
    applicationFee,
    administrationFee: 0,
    costSource: "demo-host-disclosed",
    campusDestination: `${listing.university} main campus`,
    lateTransitVerified: /MAX|Streetcar|Subway|transit/i.test(`${listing.description} ${(listing.tags || []).join(" ")}`),
    acceptsNoCreditHistory: /international|landing|temporary/i.test(`${listing.description} ${(listing.tags || []).join(" ")}`),
    ssnRequired: false,
    remoteSigning: /video|verified host|sublease/i.test(`${listing.description} ${(listing.tags || []).join(" ")}`),
    guarantorPolicy: /international|landing|temporary/i.test(`${listing.description} ${(listing.tags || []).join(" ")}`)
      ? "International guarantor or enrollment-based review accepted"
      : "",
    applicationRequirements: "Photo ID, enrollment proof, and income or guarantor information",
    verificationMethod: listing.verified ? "Host identity and listing source" : "Pending host review"
  });
});

export const seedContactRequests = [
  {
    id: "request-1",
    fromProfileId: "profile-asha",
    listingId: "listing-beaver",
    message: "Hi, I arrive Aug 12 and this looks close to my budget. Could we schedule a video call?",
    status: "pending",
    createdAt: "2026-07-13T08:30:00.000Z"
  }
];

export const seedSavedSearches = [
  {
    id: "search-1",
    profileId: "profile-asha",
    name: "Women-only private room under $950 near Penn State",
    filters: {
      university: "Penn State University",
      maxRent: 950,
      areas: ["Downtown", "West College"],
      genderPreference: "Women only",
      roomType: "Private room"
    },
    lastTriggeredAt: "2026-07-13T08:05:00.000Z"
  }
];
